### PR TITLE
Feat: CI/CD workflow to check code formatting and linting.

### PR DESCRIPTION
**Pull request by MannuVilasara**
Please review the changes @pooranjoyb 

### Addressed issue [ #21 ]

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Nice work! 🚀 @MannuVilasara

**Comment by MannuVilasara** [comment]
Thanks @pooranjoyb I will look for more contributions in future

**Comment by pooranjoyb** [comment]
> Thanks @pooranjoyb I will look for more contributions in future

You're always here in BeatBridge ❤️

**Comment by MannuVilasara** [comment]
> You're always welcomed here in BeatBridge ❤️
actually I think I used node version 14 in the lint.yml file can you please update that

**Pull request merged**
