### PR TITLE
Fix: workflow

### PR DESCRIPTION
**Pull request by MannuVilasara**
There's a little patch in workflow in this pr.

- changed the version of node to latest
- created .prettierrc for prettier check to work

### CODE REVIEW

**Comment by MannuVilasara** [comment]
fixed the issue

**Comment by pooranjoyb** [comment]
This PR is associated with #22

**Comment by pooranjoyb** [comment]
Nice Work @MannuVilasara 🚀

**Comment by MannuVilasara** [comment]
thank you very much

**Comment by pooranjoyb** [comment]
Hey @MannuVilasara , Also do check out Discussions #14
Would be glad for your comment and review 😄 👍

**Pull request merged**
