### PR TITLE
home page animation add

### PR DESCRIPTION
**Pull request by soykot2910**

### CODE REVIEW

**Comment by soykot2910** [comment]
@pooranjoyb  On scroll animation added

**Review by pooranjoyb — CHANGES_REQUESTED** [review]
image

- This one should have the `fade` animation. Checkout **[here](https://michalsnik.github.io/aos/)** for reference

image

- This image should also arrive from the right in the similar way left div arrives.

#### Rest Everything is perfect. Do these chanegs and I'll merge them 😄 
@soykot2910

**Comment by soykot2910** [comment]
@pooranjoyb fade animation added

**Comment by pooranjoyb** [comment]
Nice Work @soykot2910 🚀 
This PR closes #25

**Pull request merged**
